generate-svn-snapshot: use timeout of 15 seconds if svn2cl didn't work
Found in an internal build run, showing up as:

  svn2cl --reparagraph --stdout --include-rev -r HEAD:6087
  runtime error: file /etc/svn2cl/svn2cl.xsl line 432 element param
  xsltApplyXSLTTemplate: A potential infinite template recursion was detected.
  You can adjust xsltMaxDepth (--maxdepth) in order to raise the maximum number of nested template calls and variables/params (currently set to 3000).
  [...]

several times and tons of additional confused error output.

diff --git a/generate-svn-snapshot b/generate-svn-snapshot
--- a/generate-svn-snapshot
+++ b/generate-svn-snapshot
@@ -79,7 +79,14 @@ build_snapshot() {
   # generate changelog
   SVN_CHANGELOG=$(mktemp)
   # build GNU like changelog with svn2cl as helper tool
-  svn2cl --reparagraph --stdout --include-rev -r HEAD:$SINCE_REVISION | sed -n '/^.*\[r/,/^$/p' > $SVN_CHANGELOG
+  # timeout after 15 seconds without progress, we might be running into e.g.
+  # "xsltApplyXSLTTemplate: A potential infinite template recursion was detected."
+  timeout -k 15 15 svn2cl --reparagraph --stdout --include-rev -r HEAD:$SINCE_REVISION > $SVN_CHANGELOG
+  if [ $? -ne 0 ] ; then
+    echo '  * Sorry, generating changelog using svn2cl failed. :(' > $SVN_CHANGELOG
+  fi
+
+  sed -in '/^.*\[r/,/^$/p' > $SVN_CHANGELOG
 
   # shorten tabs at beginning of lines
   sed -i 's/\t/  /' $SVN_CHANGELOG
