Get rid of unreferenced files in release process
At a customer of mine when executing repository_checker with its
--validate-incoming option to ensure that the incoming directory
is in a sane state we noticed problems with different compression
defaults. With the recent switch to Debian/jessie for the build
infrastructure we noticed that *.tar.xz files are left behind:

| 12:12:59 Checking for leftover files in incoming directory /srv/repository/release/release-mr0.42/incoming/release-mr0.42:
| [...]
| 12:12:59 /srv/repository/release/release-mr0.42/incoming/release-mr0.42/ngcp-ngcpcfg_0.26.1.1+0~mr0.42.1.tar.xz
| [...]
| 12:12:59 Leftover files found. Needs investigation.

This is caused by the fact that executing generate-git-snapshot
on Debian/jessie by default generates a *.tar.xz file nowadays,
quoting dpkg-source(1) :

|  -Zcompression, --compression=compression
|
| 	  Specify the compression to use for created files
| 	  (tarballs and diffs).  Note that this option will not
| 	  cause existing tarballs to be recompressed, it only
| 	  affects new files. Supported  values are: gzip, bzip2,
| 	  lzma and xz.  The default is xz for formats 2.0 and
| 	  newer, and gzip for format 1.0. xz is only supported
| 	  since dpkg 1.15.5.

During the binary package build another tarball gets created via
dpkg-buildpackage's -sa option (to include the sources). In the
binary package build for an older release (like Debian/wheezy)
this won't default to *.tar.xz though. Therefore we end up with
an additional tarball, usually being *.tar.gz. Now we have a
*.tar.gz and a *.tar.xz next to each other and when simply
copying all files from binaries/ directory to the incoming
repository we end up with one unneeded tarball which is
identified as "leftover file(s) in incoming directory".

We sadly can't just default to build with dpkg-buildpackages' -b
option because then we don't get the source files in *any* binary
package build. The source files need to be present at least once
though to end up properly in the archive.

NOTE: When uploading artifacts e.g. via dput (instead of simply
copying them around) then this isn't a problem at all since
*.changes refers to the files that should be uploaded (and unused
files aren't included).

Since we execute this *only* when running through the release
repository steps (see release_repos()) it should be safe to
enable it by default. To disable this behaviour
DROP_UNUSED_DEBFILES=false still can be used.

diff --git a/scripts/build-and-provide-package b/scripts/build-and-provide-package
--- a/scripts/build-and-provide-package
+++ b/scripts/build-and-provide-package
@@ -800,6 +800,35 @@ trunk_release() {
   fi
 }
 
+# Get rid of *unused* files to avoid uploading unreferenced files to incoming
+# directory. When generating the source package on jessie this might result in
+# a *.tar.xz file. But when building the binary package for an older release
+# like wheezy this might generate a *.tar.gz file. When directly copying those
+# files into reprepro's incoming directory (e.g. for release builds) the
+# *unused* tarball will be kept around, so let's avoid that.
+drop_unused_debfiles() {
+  if [ "${DROP_UNUSED_DEBFILES:-}" = "false" ] ; then
+    echo "*** DROP_UNUSED_DEBFILES is disabled, not removing unreferenced artifact files. ***"
+    return 0
+  fi
+
+  if ! [ -x "$(which dcmd)" ] ; then
+    echo "Error: dcmd executable not available, please install devscripts package." >&2
+    exit 1
+  fi
+
+  (
+    cd "${WORKSPACE}/binaries/"
+    for file in ./* ; do
+      filename="$(basename "${file}")" # get rid of trailing ./
+      if ! dcmd ./*.changes | grep -q -- "${filename}" ; then
+        echo "*** Removing file ${filename} ***"
+        rm -f "./${filename}"
+      fi
+    done
+  )
+}
+
 release_repos() {
   echo "*** Environment variable 'release' is set, running through release steps. ***"
 
@@ -816,6 +845,9 @@ release_repos() {
     echo "*** REMOVE_FROM_RELEASE is set, trying to remove package(s) from release repository"
     REPOS="${release}" remove_packages
   fi
+
+  # get rid of files that aren't mentioned in the changes files before copying to incoming directory
+  drop_unused_debfiles
 
   cp "${WORKSPACE}/binaries/"* "${REPOSITORY}/incoming/${release}/"
   [ $? -eq 0 ] || bailout 1 "Error: Failed to copy binary packages to release directory."
