Rename global REPOSITORY to DEFAULT_REPOSITORY to support overwriting it on demand (Closes #94)
The REPOSITORY variable is used to set the main/base path for the
(reprepro) repositories (defaulting to /srv/repository).  This
REPOSITORY setting could be defined via /etc/jenkins/debian_glue.
Since we are sourcing /etc/jenkins/debian_glue in our scripts
this overwrites a possibly existing environment variables named
REPOSITORY, preventing us to overwrite the REPOSITORY setting on
demand as needed as soon as REPOSITORY is configured in
/etc/jenkins/debian_glue.

To fix that behaviour we hereby rename the REPOSITORY variable to
DEFAULT_REPOSITORY while being backwards compatible. If you have
configured REPOSITORY via /etc/jenkins/debian_glue please rename
it to DEFAULT_REPOSITORY instead. In an upcoming release we might
drop backwards compatibility.

Thanks: Jean Baptiste Favre for the bug report

diff --git a/scripts/generate-reprepro-codename b/scripts/generate-reprepro-codename
--- a/scripts/generate-reprepro-codename
+++ b/scripts/generate-reprepro-codename
@@ -12,9 +12,24 @@ bailout() {
   exit $EXIT
 }
 
+# backwards compatibility, see PR#94
+if [ -z "${REPOSITORY:-}" ] ; then
+  repository_is_missing_in_env=true
+else
+  repository_is_missing_in_env=false
+fi
+
 if [ -r /etc/jenkins/debian_glue ] ; then
   echo "*** Sourcing /etc/jenkins/debian_glue ***"
   . /etc/jenkins/debian_glue
+fi
+
+# backwards compatibility, see PR#94
+if [ -n "${REPOSITORY:-}" ] && $repository_is_missing_in_env ; then
+  echo "*** WARNING: 'REPOSITORY' set in /etc/jenkins/debian_glue but should be DEFAULT_REPOSITORY ***"
+  echo "*** WARNING: Setting DEFAULT_REPOSITORY to $REPOSITORY for backwards compatibility ***"
+  echo "*** WARNING: Please replace REPOSITORY=... in /etc/jenkins/debian_glue with DEFAULT_REPOSITORY=... ***"
+  DEFAULT_REPOSITORY="${REPOSITORY}"
 fi
 
 if [ "${BUILD_ONLY:-}" = "true" ] ; then
@@ -83,13 +98,19 @@ if [ -n "${JENKINS_DEBIAN_GLUE_VERSION:-}" ] ; then
   echo "*** Running jenkins-debian-glue version $JENKINS_DEBIAN_GLUE_VERSION ***"
 fi
 
+if [ -z "${DEFAULT_REPOSITORY:-}" ] ; then
+  echo "*** Repository variable DEFAULT_REPOSITORY is unset, using default [$DEFAULT_REPOSITORY] ***"
+  DEFAULT_REPOSITORY='/srv/repository'
+fi
+
+# REPOSITORY can overwrite DEFAULT_REPOSITORY, so define only if unset
 if [ -z "${REPOSITORY:-}" ] ; then
-  REPOSITORY='/srv/repository'
+  REPOSITORY="${DEFAULT_REPOSITORY}"
   echo "*** Repository variable REPOSITORY is unset, using default [$REPOSITORY] ***"
 fi
 
 if ! ${SUDO_CMD:-} mkdir -p "${REPOSITORY}"/conf ; then
-  echo "Error creating ${REPOSITORY}/conf (forgot to create /srv/repository and chown jenkins?)" >&2
+  echo "Error creating ${REPOSITORY}/conf (forgot to create ${REPOSITORY} and chown jenkins?)" >&2
   exit 1
 fi
 
