generate-svn-snapshot: avoid mergeWithUpstream failure with recent subversion versions
With subversion >=1.9 it fails hard if mergeWithUpstream property isn't present:

  ++ svn propget mergeWithUpstream source//debian
  svn: warning: W200017: Property 'mergeWithUpstream' not found on 'source/debian'
  svn: E200000: A problem occurred; see other errors for details

Closes #164

diff --git a/scripts/generate-svn-snapshot b/scripts/generate-svn-snapshot
--- a/scripts/generate-svn-snapshot
+++ b/scripts/generate-svn-snapshot
@@ -173,7 +173,8 @@ esac
 
 cd $ORIG_DIR
 
-debian_only="$(svn propget mergeWithUpstream source/${branch:-}/debian)"
+# subversion >=1.9 fails hard, see github issue #164
+debian_only="$(svn propget mergeWithUpstream source/${branch:-}/debian || true)"
 
 if [ -n "${SBP_OPTS:-}" ] ; then
   echo "*** Found environment variable SBP_OPTS, set to ${SBP_OPTS} ***"
