Depend on subversion-tools (<= 1.6.18dfsg-1) *or* svn2cl
svn2cl is no longer available in the unstable version of
subversion-tools, instead it's provided as separate package
as of subversion-tools 1.7.5-1.

Closes #45

diff --git a/scripts/generate-svn-snapshot b/scripts/generate-svn-snapshot
--- a/scripts/generate-svn-snapshot
+++ b/scripts/generate-svn-snapshot
@@ -30,7 +30,7 @@ if [ -z "${SVN_REVISION:-}" ] ; then
 fi
 
 if ! [ -x "$(which svn2cl)" ] ; then
-  echo "Error: svn2cl not available, please install subversion-tools." >&2
+  echo "Error: svn2cl not available, please install subversion-tools <= 1.6.18dfsg-1 or svn2cl." >&2
   exit 1
 fi
 
