Support signing source packages via $KEY_ID
Thanks: Franco Lanza <nextime@nexlab.it> for the inspiration in PR #114

diff --git a/scripts/generate-git-snapshot b/scripts/generate-git-snapshot
--- a/scripts/generate-git-snapshot
+++ b/scripts/generate-git-snapshot
@@ -399,6 +399,17 @@ quilt_cleanup
 # to get the actual requested version
 dpkg-buildpackage -uc -us -nc -d -S -i -I --source-option=--unapply-patches
 
+if [ -n "${KEY_ID:-}" ] ; then
+  echo "*** Found environment variable KEY_ID, set to ${KEY_ID:-}, signing source package ***"
+
+  if ! [ -x "$(which debsign)" ] ; then
+    echo "Error: debsign not available, please make sure the devscripts package is installed." >&2
+    exit 1
+  fi
+
+  debsign -k"${KEY_ID:-}" ../*_source.changes
+fi
+
 if [ -n "${KEEP_SOURCE_CHANGES:-}" ]; then
   echo "*** Not removing ../*_source.changes because KEEP_SOURCE_CHANGES is set ***"
 else
diff --git a/scripts/generate-svn-snapshot b/scripts/generate-svn-snapshot
--- a/scripts/generate-svn-snapshot
+++ b/scripts/generate-svn-snapshot
@@ -182,6 +182,17 @@ else
   dpkg-source --tar-ignore=\.svn -b source/${branch:-}
 fi
 
+if [ -n "${KEY_ID:-}" ] ; then
+  echo "*** Found environment variable KEY_ID, set to ${KEY_ID:-}, signing source package ***"
+
+  if ! [ -x "$(which debsign)" ] ; then
+    echo "Error: debsign not available, please make sure the devscripts package is installed." >&2
+    exit 1
+  fi
+
+  debsign -k"${KEY_ID:-}" *_source.changes
+fi
+
 # revert to original debian/changelog to avoid highly increasing version numbers with each build
 ( cd source/${branch:-} ; svn revert debian/changelog )
 
