generate-*-snapshot: provide user friendly error message if debian/changelog is missing

diff --git a/scripts/generate-git-snapshot b/scripts/generate-git-snapshot
--- a/scripts/generate-git-snapshot
+++ b/scripts/generate-git-snapshot
@@ -45,6 +45,12 @@ gbp_opts() {
 }
 
 version_information() {
+  # required for dpkg-parsechangelog
+  if ! [ -r debian/changelog ] ; then
+    echo "Error: debian/changelog could not be read. Is this really a Debian package?" >&2
+    return 1
+  fi
+
   # retrieve and adjust information
   ORIG_VERSION=$(dpkg-parsechangelog --count 1 | awk '/^Version/ {print $2}')
   INCREASED_VERSION=$(increase-version-number $ORIG_VERSION)
diff --git a/scripts/generate-svn-snapshot b/scripts/generate-svn-snapshot
--- a/scripts/generate-svn-snapshot
+++ b/scripts/generate-svn-snapshot
@@ -68,6 +68,12 @@ if [ -z "${SINCE_REVISION:-}" ] ; then
   exit 1
 fi
 
+# required for dpkg-parsechangelog
+if ! [ -r debian/changelog ] ; then
+  echo "Error: debian/changelog could not be read. Is this really a Debian package?" >&2
+  exit 1
+fi
+
 # package name
 PACKAGE=$(dpkg-parsechangelog --count 1 | awk '/^Source: / {print $2}')
 
