generate-*-snapshot: do not fail if PRE_SOURCE_HOOK is unset
While at it adjust coding style

diff --git a/scripts/generate-svn-snapshot b/scripts/generate-svn-snapshot
--- a/scripts/generate-svn-snapshot
+++ b/scripts/generate-svn-snapshot
@@ -162,19 +162,18 @@ if [ "${debian_only:-}" = "1" ] ; then
      --svn-ignore-new -rfakeroot
   )
 else
-    if ! [ -z "$PRE_SOURCE_HOOK" ] ; then
-	    if ! [ -s "$PRE_SOURCE_HOOK" ]; then
-	        echo "Could not find hook: $PRE_SOURCE_HOOK"
-	        exit 1
-	    else
-            echo "Found environment variable PRE_SOURCE_HOOK, set to ${PRE_SOURCE_HOOK}"
-	        sh $PRE_SOURCE_HOOK
-        fi
+  if ! [ -z "${PRE_SOURCE_HOOK:-}" ] ; then
+    if ! [ -s "${PRE_SOURCE_HOOK:-}" ]; then
+      echo "Error: Could not find hook: ${PRE_SOURCE_HOOK:-}" >&2
+      exit 1
+    else
+      echo "*** Found environment variable PRE_SOURCE_HOOK, set to ${PRE_SOURCE_HOOK:-} ***"
+      sh "${PRE_SOURCE_HOOK:-}"
     fi
-    dpkg-source --tar-ignore=\.svn -b source/${branch:-}
+  fi
+
+  dpkg-source --tar-ignore=\.svn -b source/${branch:-}
 fi
-
-
 
 # revert to original debian/changelog to avoid highly increasing version numbers with each build
 ( cd source/${branch:-} ; svn revert debian/changelog )
