pbuilder-hookdir/B90lintian: support execution on source files + improve error handling
If we find the Debian source package files, then execute lintian
also on the *.dsc file, allowing us to combine lintian execution
of source + binary jobs within one single step. This makes sense
esp. when we want to execute lintian from the actual build
environment/target.

lintian doesn't always return with exit code on execution errors (see
e.g. #932215 - "lintian: wrong exit code if specified profile does not
exist"). We also need to run it under bash with pipefail, otherwise
piping to tee(1) hides execution errors.

Development sponsored by Sipwise GmbH, recorded as
TT#15150 in customers' ticket system.

diff --git a/pbuilder-hookdir/B90lintian b/pbuilder-hookdir/B90lintian
--- a/pbuilder-hookdir/B90lintian
+++ b/pbuilder-hookdir/B90lintian
@@ -26,17 +26,26 @@ echo "Found package name: $PACKAGE_NAME"
 # Requires a .pbuilderrc with:
 #  export ADDITIONAL_BUILDRESULTS=(../*.lintian.txt)
 lintian_out=${BUILDDIR}/${PACKAGE_NAME}.lintian.txt
-su -c "lintian ${LINTIAN_OPTIONS:-} \"${BUILDDIR}\"/*.changes 2>&1 | tee \"${lintian_out}\"" - pbuilder \
-  || EXIT=$?
+
+DSC_EXIT=0
+if ls "${BUILDDIR}"/*.dsc &>/dev/null ; then
+  su -s /bin/bash -c "set -o pipefail; lintian ${LINTIAN_OPTIONS:-} \"${BUILDDIR}\"/*.dsc 2>&1 | tee \"${lintian_out}\"" - pbuilder \
+    || DSC_EXIT=$?
+else
+  echo "WARNING: no dsc file, not executing lintian on source package files"
+fi
+
+CHANGES_EXIT=0
+su -s /bin/bash -c "set -o pipefail; lintian ${LINTIAN_OPTIONS:-} \"${BUILDDIR}\"/*.changes 2>&1 | tee -a \"${lintian_out}\"" - pbuilder \
+  || CHANGES_EXIT=$?
+
 # We strip ANSI sequences in case lintian got --color forced
 sed -i 's%\x1B\[[0-9;]*\?[mGKH]%%g' "${lintian_out}"
 
-case ${EXIT:-0} in
-  2)
-    echo "lintian run-time error."
-    exit 2
-    ;;
-  1|*)
-    exit 0
-    ;;
-esac
+if [[ "${DSC_EXIT:-0}" =~ [01] ]] && [[ "${CHANGES_EXIT:-0}" =~ [01] ]] ; then
+  echo "Finished lintian execution [DSC_EXIT=${DSC_EXIT} CHANGES_EXIT=${CHANGES_EXIT}]"
+  exit 0
+else
+  echo "Error: lintian execution failed [DSC_EXIT=${DSC_EXIT} CHANGES_EXIT=${CHANGES_EXIT}]" >&2
+  exit 2
+fi
